title: "Maksim Lushpaev" # Your full name (large, bold, centered)
email: "me@lushpaev.ru" # Your email address
phone: "+79214041065" # Your phone number (optional)
address: "St.Petersburg, Russia" # Your address (optional)
website: "cv.lushpaev.ru" # Your website (optional)
#department: "Your Department, University, City, Country" # Department/affiliation (optional)
#affiliation: "Optional: Additional affiliation or department" # Second affiliation (optional)
#linkedin: yourprofile
#twitter: yourprofile
#github: yourprofile
telegram: @dvplm
leetcode: yourleetcodeusername
description: "CISO | InfoSec Manager" # Site description (for SEO)
baseurl: "" # GitHub Pages baseurl (leave blank for user pages)
#url: "https://yourusername.github.io" # Your GitHub Pages URL
plugins:
  - jekyll-seo-tag
markdown: kramdown
